services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres1234567890
      POSTGRES_DB: test-database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-profile:
    build:
      context: ./ms-profile
    image: ms-profile
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      api-gateway:
        condition: service_healthy

  ms-feedback:
    build:
      context: ./ms-feedback
    image: ms-feedback
    ports:
      - "8082:8082"
    restart: unless-stopped
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      ms-profile:
        condition: service_healthy

volumes:
  postgres-data:
